version: '3.8'

services:
  android-builder:
    build: .
    volumes:
      - .:/app
      - ./build:/app/build
    working_dir: /app
    command: ["./gradlew", "assembleDebug", "testDebugUnitTest"]

  android-test:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: ["./gradlew", "testDebugUnitTest"]
    depends_on:
      - android-builder